os: linux
dist: bionic
language: bash

env:
- VERSION=4.5
- VERSION=4.6
- VERSION=4.7

arch:
- amd64
- ppc64le

script: echo $VERSION $TRAVIS_CPU_ARCH
deploy:
 - provider: script
   script: 
   - echo $TRAVIS_TAG $TRAVIS_CPU_ARCH
   - export status_$TRAVIS_CPU_ARCH=$?
   skip_cleanup: true

after_success :
  script: echo "Final Stage"  
  script: echo $TRAVIS_TAG
