os: linux
dist: bionic
language: bash

env:
- VERSION=4.5
- VERSION=4.6
- VERSION=4.7

arch:
- amd64
- ppc64le

script: echo $VERSION $TRAVIS_CPU_ARCH
deploy:
 - provider: script
   script: echo $TRAVIS_TAG arch
   skip_cleanup: true
   on:
     tags: true

jobs:
 include:
  stage: Final Stage
  script: echo "Final Stage"
  deploy:
       - provider: script
         script: echo $TRAVIS_TAG
         skip_cleanup: true
         on:
           tags: true
